---

- hosts: linky_sensors
  
  tasks:
    # TODO : cas RPI 3
    # https://hallard.me/enable-serial-port-on-raspberry-pi/
     # picocom -b 1200 -d 7 -p e -f n /dev/ttyAMA0
    - block:

      - name: Désactivation de la console sur le port série serial0
        replace:
          path: /boot/cmdline.txt
          regexp: 'console=serial0(\S*) '
          replace: ''
      - name: Désactivation de la console sur le port série ttyAMA0
        replace:
          path: /boot/cmdline.txt
          regexp: 'console=ttyAMA0(\S*) '
          replace: ''

      - name: Activation du port série matériel (UART)
        ini_file:
          path: /boot/config.txt
          section: all
          option: enable_uart
          value: '1'
      
      - name: Création du groupe
        group: 
          name: linkysensor

      - name: Création de l'utilisateur
        user: 
          name: linkysensor
          group: linkysensor
          password_lock: yes

      - name: Creation des répertoires
        file: 
          name: "{{ item }}"
          state: directory
          owner: linkysensor
          group: linkysensor
        loop:
          - /opt/linky-sensor
          - /opt/linky-sensor/virtualenv
          - /opt/linky-sensor/bin
          - /opt/linky-sensor/service

      - name: Installation de Python3
        apt:
          name: 
            - python3
            - python3-pip
            - python3-venv
            - python3-setuptools
            # https://stackoverflow.com/questions/36646880/ansible-2-1-0-using-become-become-user-fails-to-set-permissions-on-temp-file/36681626
            - acl
            # https://github.com/ansible/ansible/issues/61929
            - python-setuptools

      become: yes      

    - name: Création d'un virtualenv
      become_user: linkysensor
      become: yes
      shell:  |
        python3 -m venv /opt/linky-sensor/virtualenv
      args:
        creates: /opt/linky-sensor/virtualenv/bin/activate
    
    - name: Installation des paquets Python
      become_user: linkysensor
      become: yes
      pip:
        name:
          - systemd
          - pyserial

        executable: /opt/linky-sensor/virtualenv/bin/pip3

      #  virtualenv_command: /usr/bin/python3 -m venv